[2023-09-25T16:29:09.318+0700] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crawl_dag_v01.run_my_async_task manual__2023-09-25T06:50:22.632873+00:00 [queued]>
[2023-09-25T16:29:09.324+0700] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crawl_dag_v01.run_my_async_task manual__2023-09-25T06:50:22.632873+00:00 [queued]>
[2023-09-25T16:29:09.325+0700] {taskinstance.py:1359} INFO - Starting attempt 15 of 20
[2023-09-25T16:29:09.332+0700] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): run_my_async_task> on 2023-09-25 06:50:22.632873+00:00
[2023-09-25T16:29:09.337+0700] {standard_task_runner.py:57} INFO - Started process 137 to run task
[2023-09-25T16:29:09.341+0700] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'crawl_dag_v01', 'run_my_async_task', 'manual__2023-09-25T06:50:22.632873+00:00', '--job-id', '146', '--raw', '--subdir', 'DAGS_FOLDER/crawlInvest.py', '--cfg-path', '/tmp/tmptp64dr27']
[2023-09-25T16:29:09.342+0700] {standard_task_runner.py:85} INFO - Job 146: Subtask run_my_async_task
[2023-09-25T16:29:09.388+0700] {task_command.py:415} INFO - Running <TaskInstance: crawl_dag_v01.run_my_async_task manual__2023-09-25T06:50:22.632873+00:00 [running]> on host 1f5a7ec2636d
[2023-09-25T16:29:09.450+0700] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='linhhv' AIRFLOW_CTX_DAG_ID='crawl_dag_v01' AIRFLOW_CTX_TASK_ID='run_my_async_task' AIRFLOW_CTX_EXECUTION_DATE='2023-09-25T06:50:22.632873+00:00' AIRFLOW_CTX_TRY_NUMBER='15' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-25T06:50:22.632873+00:00'
[2023-09-25T16:29:09.462+0700] {logging_mixin.py:151} INFO - ['ASG', 'BAX', 'BCF', 'BSA', 'BSH', 'DHB', 'DP2', 'DSG', 'DTK', 'EIC']
[2023-09-25T16:29:09.464+0700] {logging_mixin.py:151} INFO - etl_ingest_time_2023_09_25_16_29_09
[2023-09-25T16:29:09.467+0700] {logging_mixin.py:151} INFO - Lỗi to đùng đùng
[2023-09-25T16:29:09.468+0700] {logging_mixin.py:151} INFO - ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 17 for SQL Server' : file not found (0) (SQLDriverConnect)")
[2023-09-25T16:29:09.469+0700] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/crawlInvest.py", line 149, in run_my_async_task
    asyncio.run(crawl(Code_stock))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/airflow/dags/crawlInvest.py", line 95, in crawl
    cursor = conn.cursor()
AttributeError: 'NoneType' object has no attribute 'cursor'
[2023-09-25T16:29:09.479+0700] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=crawl_dag_v01, task_id=run_my_async_task, execution_date=20230925T065022, start_date=20230925T092909, end_date=20230925T092909
[2023-09-25T16:29:09.488+0700] {standard_task_runner.py:104} ERROR - Failed to execute job 146 for task run_my_async_task ('NoneType' object has no attribute 'cursor'; 137)
[2023-09-25T16:29:09.513+0700] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-25T16:29:09.530+0700] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
