[2023-09-25T16:45:46.546+0700] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crawl_dag_v01.run_my_async_task manual__2023-09-25T06:50:22.632873+00:00 [queued]>
[2023-09-25T16:45:46.554+0700] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crawl_dag_v01.run_my_async_task manual__2023-09-25T06:50:22.632873+00:00 [queued]>
[2023-09-25T16:45:46.554+0700] {taskinstance.py:1359} INFO - Starting attempt 21 of 26
[2023-09-25T16:45:46.563+0700] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): run_my_async_task> on 2023-09-25 06:50:22.632873+00:00
[2023-09-25T16:45:46.568+0700] {standard_task_runner.py:57} INFO - Started process 226 to run task
[2023-09-25T16:45:46.574+0700] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'crawl_dag_v01', 'run_my_async_task', 'manual__2023-09-25T06:50:22.632873+00:00', '--job-id', '159', '--raw', '--subdir', 'DAGS_FOLDER/crawlInvest.py', '--cfg-path', '/tmp/tmptsldnvzh']
[2023-09-25T16:45:46.576+0700] {standard_task_runner.py:85} INFO - Job 159: Subtask run_my_async_task
[2023-09-25T16:45:46.624+0700] {task_command.py:415} INFO - Running <TaskInstance: crawl_dag_v01.run_my_async_task manual__2023-09-25T06:50:22.632873+00:00 [running]> on host 33b2b98956f5
[2023-09-25T16:45:46.688+0700] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='linhhv' AIRFLOW_CTX_DAG_ID='crawl_dag_v01' AIRFLOW_CTX_TASK_ID='run_my_async_task' AIRFLOW_CTX_EXECUTION_DATE='2023-09-25T06:50:22.632873+00:00' AIRFLOW_CTX_TRY_NUMBER='21' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-25T06:50:22.632873+00:00'
[2023-09-25T16:45:46.701+0700] {logging_mixin.py:151} INFO - ['ASG', 'BAX', 'BCF', 'BSA', 'BSH', 'DHB', 'DP2', 'DSG', 'DTK', 'EIC']
[2023-09-25T16:45:46.702+0700] {logging_mixin.py:151} INFO - etl_ingest_time_2023_09_25_16_45_46
[2023-09-25T16:45:46.705+0700] {logging_mixin.py:151} INFO - Lỗi to đùng đùng
[2023-09-25T16:45:46.706+0700] {logging_mixin.py:151} INFO - ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 17 for SQL Server' : file not found (0) (SQLDriverConnect)")
[2023-09-25T16:45:46.707+0700] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/crawlInvest.py", line 149, in run_my_async_task
    asyncio.run(crawl(Code_stock))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/airflow/dags/crawlInvest.py", line 95, in crawl
    cursor = conn.cursor()
AttributeError: 'NoneType' object has no attribute 'cursor'
[2023-09-25T16:45:46.717+0700] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=crawl_dag_v01, task_id=run_my_async_task, execution_date=20230925T065022, start_date=20230925T094546, end_date=20230925T094546
[2023-09-25T16:45:46.726+0700] {standard_task_runner.py:104} ERROR - Failed to execute job 159 for task run_my_async_task ('NoneType' object has no attribute 'cursor'; 226)
[2023-09-25T16:45:46.744+0700] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-25T16:45:46.762+0700] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
