[2023-09-25T16:50:52.496+0700] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crawl_dag_v01.run_my_async_task manual__2023-09-25T06:50:22.632873+00:00 [queued]>
[2023-09-25T16:50:52.502+0700] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crawl_dag_v01.run_my_async_task manual__2023-09-25T06:50:22.632873+00:00 [queued]>
[2023-09-25T16:50:52.502+0700] {taskinstance.py:1359} INFO - Starting attempt 23 of 28
[2023-09-25T16:50:52.510+0700] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): run_my_async_task> on 2023-09-25 06:50:22.632873+00:00
[2023-09-25T16:50:52.515+0700] {standard_task_runner.py:57} INFO - Started process 327 to run task
[2023-09-25T16:50:52.519+0700] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'crawl_dag_v01', 'run_my_async_task', 'manual__2023-09-25T06:50:22.632873+00:00', '--job-id', '163', '--raw', '--subdir', 'DAGS_FOLDER/crawlInvest.py', '--cfg-path', '/tmp/tmpy10u5wxk']
[2023-09-25T16:50:52.521+0700] {standard_task_runner.py:85} INFO - Job 163: Subtask run_my_async_task
[2023-09-25T16:50:52.564+0700] {task_command.py:415} INFO - Running <TaskInstance: crawl_dag_v01.run_my_async_task manual__2023-09-25T06:50:22.632873+00:00 [running]> on host 33b2b98956f5
[2023-09-25T16:50:52.621+0700] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='linhhv' AIRFLOW_CTX_DAG_ID='crawl_dag_v01' AIRFLOW_CTX_TASK_ID='run_my_async_task' AIRFLOW_CTX_EXECUTION_DATE='2023-09-25T06:50:22.632873+00:00' AIRFLOW_CTX_TRY_NUMBER='23' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-25T06:50:22.632873+00:00'
[2023-09-25T16:50:52.633+0700] {logging_mixin.py:151} INFO - ['ASG', 'BAX', 'BCF', 'BSA', 'BSH', 'DHB', 'DP2', 'DSG', 'DTK', 'EIC']
[2023-09-25T16:50:52.634+0700] {logging_mixin.py:151} INFO - etl_ingest_time_2023_09_25_16_50_52
[2023-09-25T16:51:22.657+0700] {logging_mixin.py:151} INFO - Lỗi to đùng đùng
[2023-09-25T16:51:22.667+0700] {logging_mixin.py:151} INFO - ('HYT00', '[HYT00] [Microsoft][ODBC Driver 18 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
[2023-09-25T16:51:22.672+0700] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/crawlInvest.py", line 149, in run_my_async_task
    asyncio.run(crawl(Code_stock))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/airflow/dags/crawlInvest.py", line 95, in crawl
    cursor = conn.cursor()
AttributeError: 'NoneType' object has no attribute 'cursor'
[2023-09-25T16:51:22.693+0700] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=crawl_dag_v01, task_id=run_my_async_task, execution_date=20230925T065022, start_date=20230925T095052, end_date=20230925T095122
[2023-09-25T16:51:22.707+0700] {standard_task_runner.py:104} ERROR - Failed to execute job 163 for task run_my_async_task ('NoneType' object has no attribute 'cursor'; 327)
[2023-09-25T16:51:22.747+0700] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-25T16:51:22.761+0700] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
